[FILES]
FILE1=..\CSV\CHECK.CSV;P_UDO_APT_CHECK(ID,DOC_NUMB,DOC_DATE)
FILE2=..\CSV\CHECK_SP.CSV;P_UDO_APT_CHECK_SP(ID,PID,NOMEN_ID,POS_QUANT,POS_PRICE,POS_SUM,POS_NDS_RATE,POS_NDS_SUM)
[FILE]
BUF_SIZE=2
[DB]
DB_NAME=POLIK
USER=PARUS
#PSW=8F3EFD489CE449F6CD1FCF3DADFF6FDD8DDF0C0BFC93CFB95D33EF99BDD3
PREP_PROC=P_UDO_APT_CHECK_PREP
SAVE_PROC=P_UDO_APT_CHECK_SAVE
PSW=96791583BA58E03CA4A850ACF478409CC4C8B00C149B15D1F7BBCA7CD278
[OTHERS]
REGIME=0
LOG=..\IMPORT.LOG
