[FILE]
EXP_FILE_PATH=..\ITAPT\
#EXP_END_FILE=..\ITAPT\END_PARUS_EXP
#WAIT_INTERVAL=1000
#WAIT_HOUR=0
#WAIT_MIN=1
[DB]
DB_NAME=PARUS
USER=PARUS
EXP_PREP_PROC=P_UDO_ITAPT_BUFF_PREP
EXP_LOAD_VIEW=V_ITAPT_BUF_FILE
EXP_CLEAR_PROC=P_UDO_ITAPT_BUFF_CLEAR
PSW=8F3EFD489CE449F6CD1FCF3DADFF6FDD8DDF0C0BFC93CFB95D33EF99BDD3
[OTHERS]
REGIME=0
LOG=..\IMPORT.LOG
EXP_LOG=..\EXPORT.LOG
